matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.0
          - android-29
          - extra
      before_install:
        - wget http://services.gradle.org/distributions/gradle-5.6.2-bin.zip
        - unzip -qq gradle-5.6.2-bin.zip
        - export GRADLE_HOME=$PWD/gradle-5.6.2
        - export PATH=$GRADLE_HOME/bin:$PATH
        - gradle -v
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk version
        - sdk install java 11.0.4-zulu
        - sdk use java 11.0.4-zulu
      script:
        - mvn clean install -DskipTests
        - cd itf-chartizate-android
        - touch local.properties
        - gradle clean build
    - language: java
      jdk:
        - openjdk11
      script:
        - mvn clean install
