os:
  - linux
  - osx
stage: ITF - Chartizate for Java
language: java
jdk:
  - openjdk11
script:
  - mvn clean install coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_TOKEN}
  - bash <(curl -s https://codecov.io/bash)
